{{- $currentTime := (now | date "20060102150405") }}
{{- range $svc, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-{{ $svc }}"
  labels:
    app: "nginx-{{ $svc }}"
    release: "{{ $currentTime }}"
spec:
  replicas: {{ default $val.replicas 1 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "nginx-{{ $svc }}"
  template:
    metadata:
      labels:
        app: "nginx-{{ $svc }}"
    spec:
      containers:
        - name: "nginx-{{ $svc }}"
          image: nginx:{{ $val.image_tag }}
{{ end }}
