---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: myapp
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: myapp
  chart:
    git: ssh://git@github.com/jeffjen/flux-get-started
    ref: master
    path: charts/myapp
  values:
    services:
      one:
        image_tag: stable
      two:
        image_tag: stable
      three:
        image_tag: stable
      four:
        image_tag: stable

